FROM yourcontainer:0.23.0
MAINTAINER Steve Wong (EMCCODE)

ENTRYPOINT cd /isolator/isolator && \
    ./bootstrap && \
    rm -Rf build && \
    mkdir build && \
    cd build && \
    ../configure --with-mesos-root=/mesos --with-mesos-build-dir=/mesos && \
    make
